Improve "Loading" screen
rivet-gg/plugin-godot pull request #31
Opened 2023-12-29 12:28 UTC by jog1t

Closes GDT-70

![image](https://github.com/rivet-gg/plugin-godot/assets/39823706/72cc750b-a9f7-428a-bcf5-278b884650ff)

2023-12-29 17:18 UTC, NathanFlurry requested changes
Is there any case where the

2023-12-29 17:18 UTC, NathanFlurry commented on addons/rivet/devtools/dock/linking_pending.tscn
> +Browser should be opened, if not please use the link below to continue a game linking process."
We need to nail down if this activity is "signing in" or "linking game." For someone who has never used Rivet, is it immediately obvious what "linking a game" is?

2023-12-29 17:18 UTC, NathanFlurry commented on addons/rivet/devtools/dock/linking_pending.tscn
> +Browser should be opened, if not please use the link below to continue a game linking process."
Does Godot have inline links? Ideally the bottom text is something like:

```
[SPINNER] Linking game in browser

If your browser does not open, click [here].
```

2024-01-04 18:29 UTC, AngelOnFira commented on addons/rivet/devtools/dock/linking_pending.tscn
On my screen, the window looks like below. Since there's a lot of room at the top, in my head it goes to an image missing from there:

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/b7a6135b-69ee-4960-b093-e4d67fe68890.png)

Here's sort of what I'm thinking:

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/b6d3bec2-ad42-45da-a279-68cff9a930a7.png)

Maybe it shouldn't be vertically centered, but up a bit higher?

2024-01-04 18:31 UTC, AngelOnFira commented on addons/rivet/devtools/dock/login.gd
> +	)
Running cancel then trying again duplicates UI elements

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/bf6fa8e5-984b-45e6-9ed4-4dc8afe5e397.png)

2024-01-04 18:32 UTC, AngelOnFira requested changes
A few things 👍

2024-01-15 16:04 UTC, NathanFlurry approved these changes
[![cool](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/default-memes/cool.gif)](https://app.graphite.dev/macros/rivet-gg)

2024-02-03 05:09 UTC, NathanFlurry commented
@jog1t _poke_

2024-03-12 16:39 UTC, AngelOnFira commented on addons/rivet/devtools/dock/linking_pending.tscn
> +; theme_override_styles/normal = SubResource("StyleBoxFlat_3bad4")
@jog1t this was causing the plugin to not load (I imagine resources were added and not committed) so I'm taking it out for now as I look into getting this PR sorted :)

2024-03-12 18:30 UTC, AngelOnFira commented on addons/rivet/devtools/dock/login.gd
> +	var command = RivetPluginBridge.get_plugin().cli.run([
Ok, moving this to an issue to solve later. Currently, the thread & Rivet CLI will stay alive as long as Godot is open, so it's not the end of the world.

2024-03-12 18:31 UTC, AngelOnFira commented
I'm going to merge this so that it's not on your plate to check out later @jog1t 👍

2024-03-12 18:32 UTC, AngelOnFira approved these changes

2024-03-12 18:33 UTC, merged